### ISSUE TITLE
Enums in query parameters are not counted

### ISSUE THREAD

**Issue by tartakynov** [leanovate/swagger-check#5]
First of all, thank you for sharing this project with us, it's awesome and I find it very useful.

I've found that it doesn't take into account enums in query parameters, for example when I define following method it would generate completely random string as a value for the parameter:

``` yaml
/mymethod:
  get:
    parameters:
      - name: myenum
        in: query
        type: string
        enum: ['a', 'b', 'c']
        required: true
```

I'm using version 0.99.4
